### ISSUE TITLE
Node Unable to Resolve IPv6 Addresses

### ISSUE THREAD

**Issue by rotilho** [attocash/node#181]
**Investigation**:

- Ran the released version (GraalVM) locally: **Failed**
- Ran the node locally (non-GraalVM): **Worked**
- Added DNS test:
  - DNS resolution worked locally
  - `InetAddress.getByName(host)` returned expected results
  - Netty DNS resolution only worked locally
- Created a small application focused solely on DNS resolution:
  - Both AOT and JIT modes resolved DNS successfully

**Comment by Cryptoloveer** [comment]
The networking path has changed substantially since this was reported: the current node uses Ktor CIO rather than Netty for websocket connections, and DNS lookup is now isolated in `NetworkDnsResolver` using `InetAddress` on a virtual-thread dispatcher (introduced by `dcf7c1e`). That appears to remove the native-image-specific Netty resolver path described here.

Could this be retested with the current GraalVM release? If it still fails, the hostname, record type, native-image version, and resolver exception would be needed to identify a remaining issue; otherwise this looks eligible to close as resolved by the networking refactor.

**Comment by rotilho** [comment]
This turned out to be two separate issues.

The first was caused by the GraalVM agent excluding IPv6 support from the generated native binaries. After fixing that, IPv6 resolution worked correctly in the binary itself.

However, there was a second limitation: the runtime environment where I run the Atto nodes does not support IPv6, so our nodes still cannot use it in practice.

IPV6 should work fine in supported environments
